version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: metadata-editor-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: metadata-editor
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - metadata-network

volumes:
  mongodb_data:

networks:
  metadata-network:
    driver: bridge
